import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from "next/head";

const Product = () => {
    useEffect(() => {
        import('react-facebook-pixel')
            .then((x) => x.default)
            .then((ReactPixel) => {
                ReactPixel.init(process.env.NEXT_PUBLIC_FACEBOOK_PIXEL_ID)
                ReactPixel.track('ViewContent', { content_name: 'YK test product1', content_category: 'Apparel & Accessories > shirts', content_ids: ['13'], content_type: 'product', value: 1.2, currency: 'USD' });
            })
    }, [])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta property="og:title" content="YK test product1" />
                <meta property="og:description" content="Unisex Facebook T-shirt, Small" />
                <meta property="og:url" content="https://example.org/facebook" />
                <meta property="og:image" content="https://example.org/facebook.jpg" />
                <meta property="product:brand" content="Facebook" />
                <meta property="product:availability" content="in stock" />
                <meta property="product:condition" content="new" />
                <meta property="product:price:amount" content="1.2" />
                <meta property="product:price:currency" content="USD" />
                <meta property="product:retailer_item_id" content="13" />
            </Head>
            <main>
                viewContent + product meta tag sample
            </main>
        </div>
    );
};

export default Product;

