import { useState } from "react";
import Head from "next/head";

const Home = () => {
  const [productUrl, setProductUrl] = useState();
  const handleSubmit = (event) => {
    event.preventDefault();
    event.target.action = `/product/${productUrl}`;
    event.target.submit();
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form method="post" onSubmit={handleSubmit}>
          상품명: <input type="text" name="title" required /><br />
          상품 설명: <input type="text" name="description" required /><br />
          상품 이미지<input type="text" name="image" required /><br />
          상품 브랜드<input type="text" name="brand" required /><br />
          상품 stock<input type="text" name="availability" required value='in stock' /><br />
          상품 상태<input type="text" name="condition" required value='new' /><br />
          상품 가격<input type="number" name="amount" required /><br />
          통화<input type="text" name="currency" required /><br />
          상품 ID(소매점 측 ID)<input type="text" name="retailer_item_id" required value={productUrl} onChange={(e) => setProductUrl(e.target.value)} /><br />
          <button type="submit">제출</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
